name: Deploy Release 2

on:
  push:
    tags:
      - 'y*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Crear ZIP
        run: zip -r GithubActionsDemo.zip .

      - name: Crear Release
        uses: softprops/action-gh-release@v2
        with:
          files: GithubActionsDemo.zip
          
